import React from 'react'
import Head from 'next/head'
import MyNavBar from './MyNavBar'

import 'bootstrap/dist/css/bootstrap.min.css';

const Layout = ({ children }) => {
    return (
        <>
            <Head>
                <title>Testing App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MyNavBar />
            {children}
        </>
    )
}

export default Layout